# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pizza notPizza' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pizza notPizza
  pod 'Clarifai'
  pod 'SwiftyJSON', :git => 'https://github.com/IBM-Swift/SwiftyJSON.git'


end
